### ISSUE TITLE
Postgres 12 has issues (Initial migration only created the table, no fields)

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1076]
Here's my model:

```graphql
""" @model """
type User {
  id: ID!
  
  """ @db.unique """
  address: String!
  
  gender: GENDER!
  age: Int!
  
  """ @db.default: 0 """
  numFlags: Int!

  # pastSpeedDates: [User!]!
}

enum GENDER {
  MALE
  FEMALE
}
```

Here's my `.graphqlrc.yml`:

```yml
## GraphQL Config Generated by Graphback
## Please review configuration and adjust it for your own project
schema: ./backend/schema/*.graphql
extensions:
  graphback:
    model: ./backend # TODO I am not sure why this is a directory, shouldn't it point to a file?
    crud: # TODO I wonder if these should all just be enabled by default?
      create: true
      update: true
      findAll: true
      find: true
      delete: false
      subCreate: false
      subUpdate: false
      subDelete: false
    plugins:
      graphback-schema:
        format: graphql
        outputPath: ./backend/schema
      graphback-resolvers:
        format: ts
        outputPath: ./backend/resolvers
  dbmigrations:
    client: pg
    connection:
      host: ${SS_DB_HOST}
      port: ${SS_DB_PORT}
      database: ${SS_DB_NAME}
      user: ${SS_DB_USERNAME}
      password: ${SS_DB_PASSWORD}
```

I ran `graphback db`, and no errors were indicated. I looked in my database and the `user` table is there, along with the `user_id_seq`, but nothing else.
