### ISSUE TITLE
Openapi command renames input file and generated model cannot be easily consumed since missing ID type

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1242]
- when launching the openapi command, the openapi schema is renamed, while it is desirable to keep the file. 
 
```
	model/openapi.yaml.graphql
	model/openapi.yaml_processed // this is the original file
```

Also is possible to specify the output file name, getting rid of the  `.yaml.` from `openapi.graphql` ? 

- Furthermore the generated model from this openapi schema 
```
schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
```

is 
```
type Pet {
  id: Float!
  name: String!
  tag: String
}
```
while as a user I'd expect something like:

```
"""
@model
"""
type Pet {
  id: ID! 
  name: String!
  tag: String
}
```

making it straight away usable with the`graphback generate` command.
