### ISSUE TITLE
@graphback/codegen-resolvers plugin missing in package.json Error: Cannot find module '@graphback/codegen-resolvers'

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1329]
* I've installed `graphback@0.14.0-dev3`
* I've installed `graphback-cli@0.14.0-dev3`
* I've run the command `npx graphback-cli config`

This generated the following `.graphqlrc.yml`:

```yaml
## GraphQL Config Generated by Graphback
## Please review configuration and adjust it for your own project
schema: ./src/schema/*.graphql
documents: ./client/src/graphql/**/*.graphql
extensions:
  graphback:
    model: ./model/**/*.graphql
    crud:
      create: true
      update: true
      findAll: true
      find: true
      delete: false
      subCreate: false
      subUpdate: false
      subDelete: false
    plugins:
      graphback-schema:
        format: graphql
        outputPath: ./src/schema
      graphback-resolvers:
        format: ts
        outputPath: ./src/resolvers


```
Now when I run `npx graphback generate` I get the following error:

```bash
@graphback/codegen-resolvers plugin missing in package.json Error: Cannot find module '@graphback/codegen-resolvers'
```
I think `@graphback/codegen-resolvers` might not be required anymore for `graphback@0.14.0-dev3`? Perhaps the `graphback-cli` version is not being honored, I'm not sure
