### ISSUE TITLE
Subscriptions not firing

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1351]
I know that subscription filtering does not currently work, but I can't get any updates to trigger a subscription on my user type.

I believe I have everything setup properly, I've been following the documentation and templates for v0.14. I am able to run queries and mutations just fine. I'm using an ApolloServer instance, and I've given it my typeDefs generated by graphback and the resolvers. I also have the subscriptions keepAlive setting set on my ApolloServer instance.

Is there anything special that I need to do to get subscriptions to work?

**Comment by wtrocki** [comment]
CC @craicoverflow

**Comment by craicoverflow** [comment]
Hi!

Do you have subscriptions enabled in your config?

https://graphback.dev/docs/intro/config#configuration

I haven't been able to reproduce this on 0.14.2-alpha2 using the default template configuration.

**Comment by lastmjs** [comment]
Yes I do, I can see the subscription queries in my GraphiQL explorer that ApolloServer exposes, and my web socket connections on the frontend show the initial subscription query being sent and accepted. If I send an incorrect subscription query on my frontend, then it is rejected, thus showing that the subscription queries in the schema are being utilized.

So there's nothing special I have to do with the PubSub model to get this to work? I'll be digging into it more today, sorry if it might end up being some small oversight on my part.

**Comment by wtrocki** [comment]
You can pass different PubSub mechanism. We recommend Redis. Our team utilizes MQTT in production. See: https://github.com/aerogear/graphql-mqtt-subscriptions

**Comment by lastmjs** [comment]
Do I have to pass in a PubSub mechanism to get the subscriptions to work? The examples and documentation make no mention of this

**Comment by lastmjs** [comment]
I think I have found the issue, but I'm not sure if it's a bug or if I'm missing some configuration. Here is my `.graphqlrc.yml`:

```yaml
## GraphQL Config Generated by Graphback
## Please review configuration and adjust it for your own project
schema: ./src/schema/*.graphql
documents: ./client/src/graphql/**/*.graphql
extensions:
  graphback:
    model: ./model/**/*.graphql
    crud:
      create: true
      update: true
      findAll: true
      find: true
      delete: true
      subCreate: true
      subUpdate: true
      subDelete: false
    plugins:
      graphback-schema:
        format: graphql
        outputPath: ./src/schema
```
I started poking through some files to see if I could track down the source of the subscriptions not firing. I went to `node_modules/@graphback/runtime/dist/service/CRUDService.js` and looked at the update method. This is where the pubsub message gets fired whenever an update occurs.

So I added some logging and found at that the `if (this.pubSub && this.publishConfig.publishUpdate)` was returning false. this.publishConfig is set in the constructor from the `subscriptionConfig` variable. I logged this variable:

```javascript
[0] subscriptionConfig {
[0]   pubSub: PubSub {
[0]     ee: EventEmitter {
[0]       _events: [Object: null prototype] {},
[0]       _eventsCount: 0,
[0]       _maxListeners: undefined
[0]     },
[0]     subscriptions: {},
[0]     subIdCounter: 0
[0]   },
[0]   publishCreate: true,
[0]   publishUpdate: false,
[0]   publishDelete: true
[0] }
```
It looks like it is treating my subUpdate: true as false. Is it getting subUpdate and subDelete mixed up in the `.graphqlrc.yml`?
