### ISSUE TITLE
Graphback overwrote my docker-compose.yml

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1387]
I've been incorporating graphback into a project that is already using docker (Prisma to be specific). I'm still using Prisma as I slowly refactor it away. I somehow missed it, but I believe that during the graphback initialization process, my docker-compose.yml was replaced with this:

```yaml
version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgresql
      POSTGRES_DB: users
```
I was not expecting this to happen, and I was given no warning. It's only a week or two later that I've found this problem, as my normal docker containers weren't showing up.

I think a warning should be given when there is already a docker-compose file present, or perhaps rethink the docker thing entirely.
