### ISSUE TITLE
Datasync cannot be used as plugin for generating schema to file.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2076]
Due to different name loading datasync plugin from core is not possible. 
Using package name is also not possible due to `@` sign.

Error:
Cannot find module '@graphback/codegen-datasync'

er/.graphqlrc.yml:
Plain value cannot start with reserved character @ at line 26, column 7:

**Comment by machi1990** [comment]
/cc @ssd71
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by craicoverflow** [comment]
This format would work well 

```yaml
plugins:
  - name: '@graphback/codegen-schema'
    format: 'graphql'
  - name: '@graphback/datasync'
    format: 'graphql'
```

but since the plugin config is strongly associated with GraphQL CLI, this would be a major change, so the backward compatible suggestion proposed in #2077 is the best solution!
