### ISSUE TITLE
Declarative plugins

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#667]
We should be able to declare plugins in the config and pass the underlying configuration to them. No code should be required for generation. 
This will allow us to mix and match different plugins like etc. without affecting main graphback codebase.
Also, we need to migrate graphback config to GraphQL-Config

**Comment by wtrocki** [comment]
Some of the useful code here:
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/plugins.ts

**Comment by wtrocki** [comment]
I have done a spike for the approach of dynamically loading every plugin using require - where we define the naming format for the plugins

**Comment by wtrocki** [comment]
End user configuration will be based on graphql config and look as follows.
This will be also mergeable with graphql-code-generator later phase
```yml
schema:
  ./server/src/schema/index.ts:
    require: ts-node/register
documents: "./client/src/graphql/**/*.ts"
extensions:
  # Graphback configuration
  generate:
    ##  Input schema
    model: ./model
    ## Global configuration for CRUD methods
    crudSpec:
      create: true
      update: true
      findAll: true
      find: true
      delete: false
      subCreate: false
      subUpdate: false
      subDelete: false
      disableGen: false
    ## Codegen plugins
    plugins:
      - graphback-codegen-schema
        format: 'gql',
        outputPath: ./server/src/schema,
        outputFileName: 'generated'
      - graphback-codegen-client
        format: 'ts',
        outputPath: ./client/src/graphql,
      - graphback-codegen-resolvers
          format: ts
          outputPath: ./server/src/resolvers,
          types:
            resolverRootLocation: ../../generated-types
            resolverRootType: Resolvers
   
    ## Knex DB Migration config
    knexdb:
      ## See knex.js config format
      dbConfig:
        user: postgresql
        password: postgres
        database: users
        host: localhost
        port: 55432
    database: pg
```
